### ISSUE TITLE
Migrate to js_interop

### ISSUE THREAD

**Issue by deepak786** [jodinathan/typings#23]
I'm trying to migrate my flutter project with js_interop according to https://dart.dev/interop/js-interop/past-js-interop

I have the audio track.
```
import 'package:typings/core.dart' as js_binding;
import 'dart:js' as js;

List<js_binding.MediaStreamTrack> audioTracks = audioStream.getAudioTracks();
var track = audioTracks.first;
```

I have onEnded event on this track. Here I'm using `allowInterop` from `dart:js`
```
track.onended = js.allowInterop((event) {
     // Which means track.readyState = "ended"
});
```

When I'm migrating to js_interop using `toJS` as mentioned here https://dart.dev/interop/js-interop/past-js-interop#dart-js_util. `allowInterop (which is now [Function.toJS](https://api.dart.dev/stable/dart-js_interop/FunctionToJSExportedDartFunction/toJS.html))`
```
import 'dart:js_interop';

track.onended = ((event) {
      // Which means track.readyState = "ended"
}).toJS;
```
The above is giving the error `A value of type 'JSExportedDartFunction' can't be assigned to a variable of type 'dynamic Function(Event)?'`

**Comment by deepak786** [comment]
@jodinathan Any workaround?

**Comment by jodinathan** [comment]
Typings already do the `toJS` part.  

only

```dart 
track.onended = ((event) {
      // Which means track.readyState = "ended"
})
```

should work

**Comment by deepak786** [comment]
Seems to be working.
