### ISSUE TITLE
Can `typings` be used in a flutter app targeting iOS/Android?

### ISSUE THREAD

**Issue by SunlightBro** [jodinathan/typings#9]
Creating a flutter example CounterApp and adding `typings` will not compile to Android.

Maybe I'm missing something, or the pub.dev metadata is wrong and should only state WEB as supported platform.
![image](https://github.com/jodinathan/typings/assets/22753153/0f2a1664-032c-4dd5-94cf-538f63efa4a0)

**Comment by jodinathan** [comment]
Typings should work with Flutter.

Is [this](https://github.com/dart-lang/sdk/issues/52726) the problem you are having?

**Comment by SunlightBro** [comment]
No I think my issue is maybe a miss-understanding of the capabilities js_interop.

I used `ffigen` before with C and GoLang, to package a compiled library inside a Flutter-App and call the functions from dart.

That way my Flutter Android/iOS App can call go code directly, which is really useful,
when I just wanna use the official mongoDB go library maintained by the MongoDb-Team.

So when I saw js_interop and `typings`, I wanted to try to use an npm package,
and call it from my Flutter-Android-App.

**Comment by SunlightBro** [comment]
My question would be is it possible to have a flutter app compile to Andoird/iOS that calls javascript?
```dart
import 'package:typings/core.dart' as js;
//...
  void my_dart_function() {
    // Call javascript from dart to calculate the sqrt of 9
    final num sqrtOfNine = js.Math().sqrt(9);
    
    print(sqrtOfNine);
  }
```

**Comment by jodinathan** [comment]
> My question is, would it be possible to have a flutter app compile to Andoird/iOS that calls javascript?

I am no Flutter expert but I think it can with webviews or Flutter Web.
